<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TTNPL-AnkitKumarpathak" failures="1" tests="5" name="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" time="33.395" errors="0" timestamp="2023-01-16T21:58:26 IST" skipped="0">
  <testcase classname="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" name="getAppointmentsInformation_With_Invalid_LocCd" time="7.340"/>
  <system-out/>
  <testcase classname="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" name="getAppointmentsInformation_With_Invalid_RegNo" time="8.492">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest.getAppointmentsInformation_With_Invalid_RegNo(GetAppointmentsInformationTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAppointmentsInformation_With_Invalid_RegNo -->
  <system-out/>
  <testcase classname="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" name="getAppointmentsInformation_With_Invalid_DealerMapCd" time="7.751"/>
  <system-out/>
  <testcase classname="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" name="getAppointmentsInformation_With_Valid_Data" time="7.593"/>
  <system-out/>
  <testcase classname="com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest" name="getAppointmentsInformation_With_BlankData" time="2.219"/>
  <system-out/>
</testsuite> <!-- com.ttn.marutibookingandappointment.testcases.GetAppointmentsInformationTest -->
